# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: failure_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66\x61ilure_data.proto\x12*com.olist.su.channels.channelsintegrations\"o\n\x0b\x46\x61ilureData\x12\x0e\n\x06reason\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\r\n\x05retry\x18\x03 \x01(\x08\x12\x19\n\x11internal_attempts\x18\x04 \x01(\x05\x12\x12\n\nextra_data\x18\x05 \x01(\tB\x08Z\x06./;genb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'failure_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./;gen'
  _FAILUREDATA._serialized_start=66
  _FAILUREDATA._serialized_end=177
# @@protoc_insertion_point(module_scope)
