# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: listing_updated.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import event_pb2 as event__pb2
from . import failure_data_pb2 as failure__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15listing_updated.proto\x12*com.olist.su.channels.channelsintegrations\x1a\x0b\x65vent.proto\x1a\x12\x66\x61ilure_data.proto\"\xb1\x02\n\x0eListingUpdated\x12@\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x31.com.olist.su.channels.channelsintegrations.Event\x12M\n\x0c\x66\x61ilure_data\x18\x02 \x01(\x0b\x32\x37.com.olist.su.channels.channelsintegrations.FailureData\x12\x1a\n\x12\x62randed_store_slug\x18\x03 \x01(\t\x12\x14\n\x0c\x63hannel_slug\x18\x04 \x01(\t\x12\x15\n\rcanonical_sku\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x14\n\x0c\x65rror_reason\x18\x07 \x01(\t\x12\x0b\n\x03raw\x18\x08 \x01(\t\x12\x12\n\nextra_data\x18\t \x01(\tB\x08Z\x06./;genb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'listing_updated_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./;gen'
  _LISTINGUPDATED._serialized_start=103
  _LISTINGUPDATED._serialized_end=408
# @@protoc_insertion_point(module_scope)
